name: Build QA Unlocked Package

on:
  push:
    branches:
      - develop

env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
  CUMULUSCI_ORG_qa: ${{ secrets.CUMULUSCI_ORG_qa }}
  SFDX_CLIENT_ID: ${{ secrets.SFDX_CLIENT_ID }}
  SFDX_HUB_KEY: ${{ secrets.SFDX_HUB_KEY }}

jobs:
  unit_tests:
    name: "Build QA Unlocked Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sfdx
      run: |
        mkdir sfdx
        wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
        ./sfdx/install
        echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
        sfdx force:auth:sfdxurl:store -f sfdx_auth -d
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install CumulusCI
      run: |
        python -m pip install -U pip
        pip install cumulusci
    - name: Create Unlocked Package
      run: |
        cci task run update_dependencies --org feature
        cci task run create_package_version --org feature --package_type Unlocked --package_name CumulusEDAPOC-Unlocked > subscriberVersionId
    - name: Install in QA org
      run: |
        cci task run update_dependencies --org qa
        cci task run promote_package_version --version_id subscriberVersionId
        ci task run install_managed --org qa --version subscriberVersionId
