name: Release Managed Package

on:
  push:
    branches:
      - main

env:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}
  CUMULUSCI_ORG_package: '{"username": "mark.masterson@cumulusmanaged.poc", "instance_url": "https://cumulusmanagepoc-dev-ed.my.salesforce.com"}'
  SFDX_CLIENT_ID: ${{ secrets.PACKAGE_CLIENT_ID }}
  SFDX_HUB_KEY: ${{ secrets.SFDX_HUB_KEY }}

jobs:
  unit_tests:
    name: "Release Package"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install sfdx
      run: |
        mkdir sfdx
        wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
        ./sfdx/install
        echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
        sfdx force:auth:sfdxurl:store -f sfdx_auth -d -a devhub
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install CumulusCI
      run: |
        python -m pip install -U pip
        pip install cumulusci
    - name: Release Package
      run: |
        cci flow run release_package --org feature --delete-org
    - name: Install in QA org
      run: |
        sh ./bin/run.sh